
project_id = "napbrxjntjvkjwlcpwql"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
webhook_keys = []

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[functions]]
name = "generate-image"
verify_jwt = false

[[functions]]
name = "image-upscaler"
verify_jwt = false

