
[build]
  publish = "dist"
  command = "npm run build"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Add custom 404 handling
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# Ensure proper caching for static assets
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add security headers with payment-related domains allowed
[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Content-Security-Policy = "frame-ancestors 'none'; default-src 'self'; connect-src 'self' https://napbrxjntjvkjwlcpwql.supabase.co wss://*.supabase.co https://pay.drutopay.com https://*.functions.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; form-action 'self' https://pay.drutopay.com;"
