
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://napbrxjntjvkjwlcpwql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcGJyeGpudGp2a2p3bGNwd3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzQ1MDAsImV4cCI6MjA1NTgxMDUwMH0.NtgbBqj9dCCiTX4R3_OO77x2psw7UqbJBW4rLmpFS0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
