
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbtvvvbejvyqfvucqnej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxidHZ2dmJlanZ5cWZ2dWNxbmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTQ5MjgsImV4cCI6MjA1NzQ3MDkyOH0.-RDGpb3LnEnDMZ-8DfIh98VHwt8s62pMJPwA-JujfjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
